### ISSUE TITLE
seeing "can't find ext4 filesystem" messages on compute nodes

### ISSUE THREAD

**Issue by vicenteg** [vicenteg/ansible-openstack#43]
[16361.693774] EXT4-fs (nbd11): VFS: Can't find ext4 filesystem
[16361.829370] block nbd11: Unexpected reply (ffff8803de21dc08)

**Comment by splucena** [comment]
I'm experiencing same error, have you found the solution?

**Comment by vicenteg** [comment]
Sorry, no - I have not worked on this repository in some time. Are you installing on SeaMicro?

**Comment by sitiaminahabdullah** [comment]
i've got the same message :(

**Comment by vicenteg** [comment]
This repo is no longer being maintained. Feel free to fork and fix.
